### ISSUE TITLE
Create dogonlanguages community on zenodo

### ISSUE THREAD

**Issue by xrotwang** [dogonlanguages/meta#1]
@bambooforest can we do this with our institutional github/zenodo user account? Since dogonlanguages.org is hosted with our institute, this would make sense, I think.

**Comment by bambooforest** [comment]
@xrotwang - i suppose i can do this with my Zenodo account (they offer a function for it for individuals). Then I could tag all existing Dogon materials already in Zenodo -- along the lines I suppose of what you set up for LDH. OK?

**Comment by xrotwang** [comment]
The problem with using individual accounts is that **only** the uploading account will ever be able to edit metadata. And what's more problematic: For content uploaded automatically from github, the account registering the repos on Zenodo will be the owner of all uploads - **not** the acount used to make the actual releases on GitHub - which means that you may make an upload to zenodo, which you end up not being able to edit the metadata.

**Comment by xrotwang** [comment]
I'd hope that at some point Zenodo will implement functionality to transfer ownership of uploads. But so far, that hasn't happened.

**Comment by bambooforest** [comment]
So what do you suggest?

**Comment by xrotwang** [comment]
I'd use our institutional account to register the repos on zenodo and create the community and give you access to it?

There's hope for a better future:
- https://github.com/zenodo/zenodo/issues/151

**Comment by bambooforest** [comment]
sgtm.

**Comment by xrotwang** [comment]
https://zenodo.org/communities/dogonlanguages/
